site_name: Spectator Docs
pages:
- Home: index.md
- 'Getting Started':
  - 'Meter Types':
    - Counters: Counter-Usage.md
    - Timers: Timer-Usage.md
    - Gauges: Gauge-Usage.md
    - 'Distribution Summaries': Distribution-Summary-Usage.md
  - Testing: Testing.md
  - 'Netflix Integration': Netflix-Integration.md
  - 'Servo Comparison': Servo-Comparison.md
- Extensions:
  - 'Buffer Pools': ext/jvm-buffer-pools.md
  - 'Garbage Collection': ext/jvm-gc.md
  - 'GC Causes': ext/jvm-gc-causes.md
  - 'Memory Pools': ext/jvm-memory-pools.md
  - 'Log4j2 Appender': ext/log4j2.md
- Registries:
  - Metrics3: registry/metrics3.md
  - Servo: registry/servo.md
  - TDigest: registry/tdigest.md
theme: readthedocs
extra_css:
- css/custom.css
markdown_extensions:
- admonition
